### ISSUE TITLE
How to carry out channel pruning?

### ISSUE THREAD

**Issue by betterhalfwzm** [Zx55/dmcp#1]
How to prune 4 channels or 8 channels at a time so that the number of reserved channels is a multiple of 4? How can I set up?

**Comment by betterhalfwzm** [comment]
@Zx55 Can you help me?

**Comment by Zx55** [comment]
Hi, you can set channel offset [here](https://github.com/Zx55/dmcp/blob/8bf815d5c7c1b1d9d4c89c38a365c29cad86f9e5/models/dmcp/alpha_op.py#L95). 

You could try to change this function like 
```python
def _get_ch_indice(min_width, max_width, width_offset, max_ch, channel_offset=None):
    if channel_offset is None:
        ch_offset = int(width_offset * max_ch / max_width)
        num_offset = int((max_width - min_width) / width_offset + 1e-4)
        min_ch = max_ch - (ch_offset * num_offset)
        assert min_ch > 0
    else:
        ch_offset = channel_offset
        min_ch = ch_offset
        num_offset = int((max_ch - min_ch) / ch_offset + 1e-4)
    
    # ...
```

just make sure
```python
assert indice[0] == min_ch
assert indice[-1] == max_ch
```

**Comment by betterhalfwzm** [comment]
> ```python
> channel_offset
> ```

Thank you for your reply. If pruning is carried out in multiples of 4,  will it have a great impact on the accuracy? @Zx55

**Comment by Zx55** [comment]
> If pruning is carried out in multiples of 4, will it have a great impact on the accuracy?

No, it won't.

**Comment by betterhalfwzm** [comment]
> > If pruning is carried out in multiples of 4, will it have a great impact on the accuracy?
> 
> No, it won't.

I will try it. Thank you very much!!

**Comment by betterhalfwzm** [comment]
@Zx55 I change the code like this:

    def _get_ch_indice(min_width, max_width, width_offset, max_ch, channel_offset=4):
        if channel_offset is None:
            print('none')
            print(channel_offset)
            ch_offset = int(width_offset * max_ch / max_width)
            num_offset = int((max_width - min_width) / width_offset + 1e-4)
            min_ch = max_ch - (ch_offset * num_offset)
            assert min_ch > 0
        else:
            print(channel_offset)
            ch_offset = channel_offset
            min_ch = ch_offset
            num_offset = int((max_ch - min_ch) / ch_offset + 1e-4)
        indice = []
        for i in range(num_offset + 1):
            indice.append(min_ch + i * ch_offset)
        assert indice[0] == min_ch
        assert indice[-1] == max_ch
        return sorted(list(set(indice)))       
     
But i got the channels like this, There's still something that can't be divided by four，Need your help!! Thx!!!!!!!! @Zx55 
{'conv1': 11, 'conv_last': (158, 1715), '0': {'conv2': (11, 11), 'conv3': (11, 6)}, '1': {'conv1': (6, 34), 'conv2': (34, 34), 'conv3': (34, 15)}, '2': {'conv1': (15, 21), 'conv2': (21, 21), 'conv3': (21, 15)}, '3': {'conv1': (15, 98), 'conv2': (98, 98), 'conv3': (98, 28)}, '4': {'conv1': (28, 30), 'conv2': (30, 30), 'conv3': (30, 28)}, '5': {'conv1': (28, 41), 'conv2': (41, 41), 'conv3': (41, 28)}, '6': {'conv1': (28, 155), 'conv2': (155, 155), 'conv3': (155, 56)}, '7': {'conv1': (56, 63), 'conv2': (63, 63), 'conv3': (63, 56)}, '8': {'conv1': (56, 71), 'conv2': (71, 71), 'conv3': (71, 56)}, '9': {'conv1': (56, 57), 'conv2': (57, 57), 'conv3': (57, 56)}, '10': {'conv1': (56, 287), 'conv2': (287, 287), 'conv3': (287, 65)}, '11': {'conv1': (65, 70), 'conv2': (70, 70), 'conv3': (70, 65)}, '12': {'conv1': (65, 58), 'conv2': (58, 58), 'conv3': (58, 65)}, '13': {'conv1': (65, 330), 'conv2': (330, 330), 'conv3': (330, 182)}, '14': {'conv1': (182, 232), 'conv2': (232, 232), 'conv3': (232, 182)}, '15': {'conv1': (182, 201), 'conv2': (201, 201), 'conv3': (201, 182)}, '16': {'conv1': (182, 630), 'conv2': (630, 630), 'conv3': (630, 158)}}

**Comment by Zx55** [comment]
maybe you can try to use [make_divisible](https://github.com/Zx55/dmcp/blob/master/models/slimmable/us_ops.py#L10) when loading channel config in adaptive models.
