### ISSUE TITLE
error

### ISSUE THREAD

**Issue by betterhalfwzm** [Zx55/dmcp#2]
(torch1.4) wangzhaoming@ubuntu:~/work_code/dmcp$ python main.py --mode train --data /data2/ImageNet --config config/mbv2/dmcp.yaml --flops 87
/home/wangzhaoming/work_code/dmcp/utils/tools.py:62: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
Traceback (most recent call last):
  File "main.py", line 71, in <module>
    main()
  File "main.py", line 42, in main
    tools.init(config)
  File "/home/wangzhaoming/work_code/dmcp/utils/tools.py", line 27, in init
    dist.init_dist(config.distributed.enable)
  File "/home/wangzhaoming/work_code/dmcp/utils/distributed.py", line 30, in init_dist
    rank = int(os.environ['RANK'])
  File "/home/wangzhaoming/anaconda3/envs/torch1.4/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'RANK'
@Zx55

**Comment by betterhalfwzm** [comment]
Another error: AttributeError: 'EasyDict' object has no attribute 'max_iter' 
@Zx55

**Comment by betterhalfwzm** [comment]
Another error: AttributeError: 'EasyDict' object has no attribute 'warmup_steps'
@Zx55

**Comment by Zx55** [comment]
1. if you'd like to init distribution system through environment variable, maybe you can change the dist_url to 'env://' [here](https://github.com/Zx55/dmcp/blob/8bf815d5c7c1b1d9d4c89c38a365c29cad86f9e5/utils/distributed.py#L31). You can see official [example](https://github.com/pytorch/examples/tree/master/imagenet).
Or you can run code with single card, and change the distributed.enable = False in config file.

2. can you give a more detailed error message?

3. maybe you delete 'warmup_steps' setting in config file

**Comment by betterhalfwzm** [comment]
> 1. if you'd like to init distribution system through environment variable, maybe you can change the dist_url to 'env://' [here](https://github.com/Zx55/dmcp/blob/8bf815d5c7c1b1d9d4c89c38a365c29cad86f9e5/utils/distributed.py#L31). You can see official [example](https://github.com/pytorch/examples/tree/master/imagenet).
>    Or you can run code with single card, and change the distributed.enable = False in config file.
> 2. can you give a more detailed error message?
> 3. maybe you delete 'warmup_steps' setting in config file

@Zx55 
1.Set false ,it works.
2. I think there is a problem with config，you should check it.
Traceback (most recent call last):
  File "main.py", line 71, in <module>
    main()
  File "main.py", line 54, in main
    train(config, runner, loaders, checkpoint, tb_logger)
  File "main.py", line 23, in train
    arch_lr_scheduler = tools.get_lr_scheduler(optimizer[1], config.arch_lr_scheduler)
  File "/home/wangzhaoming/work_code/dmcp/utils/tools.py", line 196, in get_lr_scheduler
    optimizer, config.max_iter, config.min_lr, config.base_lr,
AttributeError: 'EasyDict' object has no attribute 'max_iter'
3.I do not change config file,I think there is a problem with config，you should check it.
config file:
training:
    epoch: 40
    sandwich:
        sample_type: offset
        max_width: &max_width 1.5
        min_width: &min_width 0.1
        width_offset: &width_offset 0.1
        num_sample: 4
    label_smooth: 0.1
    distillation:
        enable: true
        temperature: 1
        loss_weight: 1
        hard_label: False

arch:
    target_flops: None
    train_freq: 1
    sample_type: [max, min, scheduled_random, scheduled_random]
    floss_type: log_l1
    flop_loss_weight: 0.1
    num_flops_stats_sample: 3000
    num_model_sample: 5

validation:
    width: [*max_width]
    calibration:
        enable: True
        num_batch: 5

evaluation:
    width: [*max_width]
    calibration:
        enable: True
        num_batch: 5

model:
    type: DMCPMobileNetV2
    kwargs:
        num_classes: &num_classes 1000
        input_size: &input_size 224
        width: [*min_width, *max_width, *width_offset]
        prob_type: sigmoid

    runner:
        type: DMCPRunner

recover:
    enable: False
    checkpoint: None

distributed:
    enable: False

optimizer:
    momentum: 0.9
    weight_decay: 0.00004
    nesterov: True
    no_wd: True

lr_scheduler:
    base_lr: 0.2
    warmup_lr: 0.5
    warmup_steps: 1000
    min_lr: 0.08

arch_lr_scheduler:
    base_lr: 0.5
    warmup_lr: 0.5
    min_lr: 0.1

dataset:
    type: ImageNet
    augmentation:
        test_resize: 256
        color_jitter: [0.2, 0.2, 0.2, 0.1]
    workers: 4
    batch_size: 64
    num_classes: *num_classes
    input_size: *input_size

logging:
    print_freq: 50

random_seed: 0
save_path: ./results

**Comment by Zx55** [comment]
It's caused by a typo.

**Comment by betterhalfwzm** [comment]
> It's caused by a typo.

  
@Zx55 
File "main.py", line 71, in <module>
    main()
  File "main.py", line 54, in main
    train(config, runner, loaders, checkpoint, tb_logger)
  File "main.py", line 23, in train
    arch_lr_scheduler = tools.get_lr_scheduler(optimizer[1], config.arch_lr_scheduler)
  File "/home/wangzhaoming/work_code/dmcp/utils/tools.py", line 197, in get_lr_scheduler
    config.warmup_lr, config.warmup_steps, last_iter=last_iter)
AttributeError: 'EasyDict' object has no attribute 'warmup_steps'

**Comment by Zx55** [comment]
Updated. Can you try again? I run the code well now.

**Comment by betterhalfwzm** [comment]
> Updated. Can you try again? I run the code well now.

Yes, it works, singel gpu too slowly. but distributed:   enable: True, errors remian exiting, i have try your suggestion. Can you solve it? Thank you very much. @Zx55 
Traceback (most recent call last):
  File "main.py", line 80, in <module>
    main()
  File "main.py", line 51, in main
    tools.init(config)
  File "/home/wangzhaoming/work_code/dmcp/utils/tools.py", line 27, in init
    dist.init_dist(config.distributed.enable)
  File "/home/wangzhaoming/work_code/dmcp/utils/distributed.py", line 31, in init_dist
    rank = int(os.environ['RANK'])
  File "/home/wangzhaoming/anaconda3/envs/torch1.4/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'RANK'

**Comment by Zx55** [comment]
> but distributed: enable: True, errors remian exiting

1. if you run code with multi-card on a single node, you could try

    ```bash
    CUDA_VISIBLE_DEVICES=0 RANK=0 WORLD_SIZE=2 python main.py ...
    CUDA_VISIBLE_DEVICES=1 RANK=1 WORLD_SIZE=2 python main.py ... 
    ```

2. if you run code on multi nodes, maybe you can pass ip and port of master node (e.g: "tcp://10.10.10.1:8000") through command line args 

    ```bash
    # on master  
    CUDA_VISIBLE_DEVICES=0 RANK=0 WORLD_SIZE=2 python main.py --url tcp://10.10.10.1:8000 ...

    # on slave
    CUDA_VISIBLE_DEVICES=0 RANK=1 WORLD_SIZE=2 python main.py --url tcp://10.10.10.1:8000 ...
    ```

    you should add argments to parser in `main.py` and set it [here](https://github.com/Zx55/dmcp/blob/master/utils/distributed.py#L31)

    or just use slurm 
    
    ```bash
    srun --partition=YOUR_PARTITION --mpi=pmi2 --gres=gpu:4 -n12 --ntasks-per-node=4 --job-name=dmcp --kill-on-bad-exit=1 python main.py ...
    ```
