### ISSUE TITLE
Why pruned mobilenet-v2 DMCP 300M and 211M has higher parameter count?

### ISSUE THREAD

**Issue by atrah22** [Zx55/dmcp#5]
Hello,
I could understand that the DMCP prunes channel layer by layer and hence the MAC(or FLOP) count decreases. I found that DMCP 211M and 300M pruned from Mobilenet-V2 has higher parameter count than Mobilenet-V2. Why the parameter count increases ?

Classification   Models | FLOPS (G) | Params (M) | TOP_acc@1 | TOP_acc@5
-- | -- | -- | -- | --
Mobilenet-V2 | 0.858 | 3.48 | 71.87 | 90.294
DMCP 300M | 0.600 | 5.3 | 73.48 | 91.10
DMCP 211M | 0.420 | 4.2 | 71.60 | 89.95

Best Regards,
Atul

**Comment by Zx55** [comment]
Hi, what's the width of Mobilenet-v2 in your first result? DMCP performs pruning on Mobilenet-V2 1.5x.
Also, DMCP prefers retaining more channels in deep layers, where has more parameters.

**Comment by atrah22** [comment]
Hello,
Its the dafault torchvision Mobilenet-V2 1.0x model.
1) In the paper Table 6, The DMCP Mobilenet-v2 models are compared with 1.0x and lower scale (0.75x,0.5x etc). In that table iis the DMCP mobilenet-v2 trained from Mobilenet-1.5x?
2) Can I receive the DMCP mobilenet-v2 trained from Mobilenet-v2 1.0x for fair comparison. I am refering to Figure 5 on the paper and Table 2. MBV2 1.0x-210M and additionally MBV2 1.5x-300M.

**Comment by Zx55** [comment]
> In the paper Table 6, The DMCP Mobilenet-v2 models are compared with 1.0x and lower scale (0.75x,0.5x etc). In that table iis the DMCP mobilenet-v2 trained from Mobilenet-1.5x?

Yes.

> Can I receive the DMCP mobilenet-v2 trained from Mobilenet-v2 1.0x for fair comparison.

Do you mean the checkpoint of mbv2-1.0x-210M? 

1. I could not find the checkpoint of mbv2-1.0x-210m. Instead, you can train dmcp mbv2-1.0x-210m by changing `max_width` in [config file](https://github.com/Zx55/dmcp/blob/49629e37aec622762d27e79878ab17dfe9c8694d/config/mbv2/dmcp.yaml#L5).

2. You can download the checkpoint of mbv2-1.5x-300m from [here](https://github.com/Zx55/dmcp/releases).

**Comment by atrah22** [comment]
Hello,
Yes check point of mbv2-1.0x-210M and 300M
I have tested already and used mbv2-1.5x-210M and 300M.
Okay, I will then prune from scratch mbv2-1.0x 210M.
Thankyou
