### ISSUE TITLE
About parameters of pruned models

### ISSUE THREAD

**Issue by JiaxiongQ** [Zx55/dmcp#7]
Hi! Great work!
Could you show the comparison of parameters?  e.g. ResNet-50

**Comment by Zx55** [comment]
Hi, I add `calc_model_parameters()` to codebase. Now you can run `python --mode calc_params ...` to perform parameters calculation on pruned models.

Parameters of pruned ResNet-50: 
|flops |parameters (M)|
|:----:|:----:|
|279M|4.27|
|1.1G|14.47|
|2.2G|21.31|
|2.8G|23.18|
|4.09G (baseline)|25.56|

**Comment by JiaxiongQ** [comment]
Thanks! I'll close this issue.
